### ISSUE TITLE
Strings

### ISSUE THREAD

**Issue by Zireael07** [sleibrock/zigtoys#1]
> For starters, you might want to forget about the idea of strings entirely

That's interesting, as your approach is completely opposite to: https://blog.battlefy.com/zig-made-it-easy-to-pass-strings-back-and-forth-with-webassembly

**Comment by ste5e99** [comment]
Howdy. When I first started this project, I was pretty amateurish to the world, and since I didn't have any hard, concrete resources to use at the time, much of my findings here are self-discovery only. Most demo toys I build here are based on HTML5 Canvas, and as such I try to avoid allocators where possible. As such, if at any point I deal with strings, I first try to look at ways of dealing with them without the use of allocators, ie fix-sized input/output arrays.

The link you posted is a solution you can use to implement copying strings from JavaScript to WASM memory space. It wraps on the basic Zig allocation process, but induces a failpoint with `@panic` (I prefer catching Zig errors instead of straight-up crashing the program). I wouldn't take my repo as a serious and official documentation, but more as the personal experiences of someone who had to learn from very little available.

I appreciate the reach-out with some new insights.
